spring:
  application:
    name: Abhilasha Chebolu Figueroa
  profiles:
    active: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
server:
  port: 8080
