spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    LiveReload:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    url: jdbc:h2:file:./data/testdb
    user: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true