when:
  - event: [push, pull_request_closed, manual]
    branch: [main, woodpecker-ci-workflow-testing]

steps:
  - name: build-app
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: registry.mocalabs.dev
      repo: registry.mocalabs.dev/mocalabs/abhilasha
      dockerfile: Dockerfile
      context: .
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:8}
      cache: true
      skip_tls_verify: false
      build_args:
        - COMMIT_SHA=${CI_COMMIT_SHA}
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
